name: Auto Git Pull to GCP

on:
  push:
    branches:
      - main

jobs:
  git-pull:
    runs-on: ubuntu-latest

    steps:
      - name: Pull latest code and deploy to nginx
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 34.47.97.72
          username: qkrrjsgud49
          key: ${{ secrets.GCP_PRIVATE_KEY }}
          script: |
            cd ~/capstone/ROOMIT
            git pull origin main
            npm install
            npm run build
            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/
